### ISSUE TITLE
Elements not aligned in footer on mobile - see screenshot

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#13]
See subject line
![screenshot_20161207-132548_ink_li](https://cloud.githubusercontent.com/assets/15867551/20967720/327f30de-bc81-11e6-929d-2be3d1ba2127.jpg)

**Comment by wisniowski** [comment]
This issue should solve itself once there'll be remaining two items added
(terms of use, privacy policy). The issue is visible now is because the CSS
code finds "last two items" and style them accordingly to the initial
design.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 13:29 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Okay, sounds good. I'll close this for now.
