### ISSUE TITLE
Buttons not aligning in mobile on product page

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#46]
![screenshot](https://cloud.githubusercontent.com/assets/15867551/21175012/93c7513c-c1e0-11e6-921a-8608132d0ae3.png)

**Comment by wisniowski** [comment]
That's because of custom column structure added by someone. I could fix it,
but I am not sure if it won't break any other section of this page.
Ideally, please add some unique class (like "links") to the parent item so
I can use it as targeting selector.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-14 9:35 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by AneliyaPPetkova** [comment]
This is actually a content editing issue, so there is no need of fixing the styles. It is already fixed on UAT, so please test :)

We just changed the previous 50%-50% layout with a 4-column layout and we changed the Buttons alignment to "Center" for both buttons: http://screencast.com/t/qwkO27vEvo

Cheers :)

**Comment by michehrlich** [comment]
Thanks! Confirm fixed, closing.
